// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data.EF;

namespace Store.Data.EF.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProdStore.Data.OrderDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProdStore.Data.OrderItemDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProdStore.Data.ProductDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Articul")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Volume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Articul = "6589100",
                            Category = "Сладости",
                            Image = "https://gotoshop.ua/img/p/2020/09/121032/1834638-121032-batonchik-snickers-super-z-arakhisom-u-molochnomu-shokoladi-1125g.jpg?t=t1599687385",
                            Name = "Батончик Snickers Super з арахісом у молочному шоколаді",
                            Price = 17.2m,
                            Volume = "112,5г"
                        },
                        new
                        {
                            Id = 2,
                            Articul = "5232178",
                            Category = "Напитки",
                            Image = "https://www.morshynska.ua/images/products/bottle/negaz/pet_033.png",
                            Name = "Вода мінеральна «Моршинська» негазована",
                            Price = 7.8m,
                            Volume = "0,5л"
                        },
                        new
                        {
                            Id = 3,
                            Articul = "7895030",
                            Category = "Сладости",
                            Image = "https://market.rukavychka.ua/image/cache/catalog/tovaru/cukerki-rafaello-150g-tm-ferrero-507030201-700x500.jpg",
                            Name = "Цукерки Raffaello",
                            Price = 9.5m,
                            Volume = "150г"
                        },
                        new
                        {
                            Id = 4,
                            Articul = "0013872",
                            Category = "Напитки",
                            Image = "https://img.fozzyshop.com.ua/rivne/25416-large_default/sok-sandora-apelsinovyj-05l.jpg",
                            Name = "Сік Sandora апельсиновий",
                            Price = 5.2m,
                            Volume = "1л"
                        },
                        new
                        {
                            Id = 5,
                            Articul = "8999741",
                            Category = "Напитки",
                            Image = "https://www.korzyna.com/img/600/744/resize/6/9/694510DSCF8905.jpg",
                            Name = "Напій Coca-Cola",
                            Price = 8.1m,
                            Volume = "1л"
                        },
                        new
                        {
                            Id = 6,
                            Articul = "9805246",
                            Category = "Напитки",
                            Image = "https://www.korzyna.com/img/600/744/resize/5/2/520407DSCF6788.jpg",
                            Name = "Напій енергетичний Red Bull",
                            Price = 17.54m,
                            Volume = "0,5л"
                        },
                        new
                        {
                            Id = 7,
                            Articul = "0018539",
                            Category = "Напитки",
                            Image = "https://images.ua.prom.st/3078569493_w700_h500_gazirovannyj-napitok-fanta.jpg",
                            Name = "Напій Fanta Orange",
                            Price = 24.7m,
                            Volume = "1л"
                        },
                        new
                        {
                            Id = 8,
                            Articul = "4396524",
                            Category = "Сыр",
                            Image = "https://img2.zakaz.ua/food.1612550279.ad72436478c_2021-02-07_Tatyana_L/food.1612550279.SNCPSG10.obj.0.1.jpg.oe.jpg.pf.jpg.350nowm.jpg.350x.jpg",
                            Name = "Сир Premialle «Фета» 45%",
                            Price = 51.99m,
                            Volume = "230г"
                        },
                        new
                        {
                            Id = 9,
                            Articul = "4028609",
                            Category = "Сладости",
                            Image = "https://www.i-igrushki.ru/upload/iblock/351/351d149b382875999294dcd2ca848117.jpg",
                            Name = " Яйце шоколадне Kinder «Сюрприз»",
                            Price = 24.59m,
                            Volume = "20г"
                        },
                        new
                        {
                            Id = 10,
                            Articul = "5745016",
                            Category = "Сладости",
                            Image = "https://images.ua.prom.st/2217550375_zhevatelnaya-rezinka-orbit.jpg",
                            Name = "Гумка жувальна Orbit Tabs «М'ята»",
                            Price = 10.39m,
                            Volume = "27г"
                        },
                        new
                        {
                            Id = 11,
                            Articul = "9002917",
                            Category = "Сладости",
                            Image = "https://gastronom.com.ua/images/sets/803_av.jpg",
                            Name = "Батончик Nestle Lion",
                            Price = 7.8m,
                            Volume = "42г"
                        });
                });

            modelBuilder.Entity("ProdStore.Data.RoleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("ProdStore.Data.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Password = "123456",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ProdStore.Data.OrderItemDto", b =>
                {
                    b.HasOne("ProdStore.Data.OrderDto", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProdStore.Data.UserDto", b =>
                {
                    b.HasOne("ProdStore.Data.RoleDto", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProdStore.Data.OrderDto", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProdStore.Data.RoleDto", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
